apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-demo
        version: v1
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        api-demo: "yes"
      containers:
      - image: huanwei/api-demo-tini:v1
        imagePullPolicy: IfNotPresent
        name: api-demo
        #ports:
        #- containerPort: 8082
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /harmonycloud/api-demo
          name: install
      volumes:
      - name: tmp
        hostPath:
          path: /tmp
          type: Directory
      - name: install
        hostPath:
          path: /harmonycloud/api-demo
          type: DirectoryOrCreate